# Generated by Django 5.1.1 on 2024-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('created_t', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in progress', 'in progress'), ('completed', 'completed'), ('error', 'error')], default='in progress')),
            ],
        ),
    ]
