# Generated by Django 5.1.1 on 2024-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField()),
                ('imported_t', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('created_t', models.BigIntegerField()),
                ('last_modified_t', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('brands', models.CharField(max_length=255)),
                ('categories', models.TextField(max_length=255)),
                ('labels', models.TextField(max_length=255)),
                ('cities', models.TextField(blank=True, null=True)),
                ('purchase_places', models.TextField()),
                ('ingredients_text', models.TextField()),
                ('traces', models.TextField()),
                ('stores', models.TextField(max_length=255)),
                ('serving_size', models.TextField(max_length=255)),
                ('serving_quantity', models.FloatField()),
                ('nutriscore_score', models.FloatField()),
                ('nutriscore_grade', models.CharField(max_length=2)),
                ('main_category', models.TextField(max_length=255)),
                ('image_url', models.URLField(max_length=255)),
                ('status', models.CharField(choices=[('trash', 'trash'), ('draft', 'draft'), ('published', 'published')], max_length=9)),
            ],
        ),
    ]
