# Generated by Django 5.1.1 on 2024-10-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.PositiveBigIntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='serving_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
