# Generated by Django 5.1.1 on 2024-10-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_code_alter_product_nutriscore_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutriscore_score',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='serving_quantity',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
