# Generated by Django 5.1.1 on 2024-10-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_t',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified_t',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
