# Generated by Django 5.1.1 on 2024-10-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_categories_alter_product_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
